# Generated by Django 6.0.4 on 2026-05-26 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Цена за километр (₽)')),
                ('minimum_price', models.DecimalField(decimal_places=2, default=150.0, max_digits=8, verbose_name='Минимальная цена (₽)')),
                ('boarding_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Посадочный тариф (₽)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Настройки тарифа',
                'verbose_name_plural': 'Настройки тарифа',
            },
        ),
    ]
